version: '3.8'

services:
  book-app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    links: 
      - db
    environment:
      - DB_PASSWORD=root

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

networks:
  my-network:
    driver: "bridge"