version: '3.8'

services:
  # Book app.
  book-app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
        db:
         condition: service_healthy
    environment:
      - DB_PASSWORD=root
    networks:
      - books-network

 

  # Mysql with test data.
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-p$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10
    networks:
      books-network:
          aliases:
            - db

networks:
  books-network:
    driver: "bridge"